---
title: "alt-flash vs flashier"
author: "Joonsuk Kang"
date: "2021-12-06"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


# some functions

```{r}
source('code/alt-flash-ebnm-2021-1206.R')
```


```{r}
library(tidyverse)

plotL <- function(A.l, title){

  K <- ncol(A.l)
  n <- nrow(A.l)
  
  data.frame(L=c(A.l),
             factor=rep(1:K, each=n),
             x=rep(1:n, times=K)) %>%
    mutate(factor=as.factor(factor)) -> df.plot
  
  df.plot %>%
    ggplot()+
    geom_line(aes(x=x, y=L, group=factor, col=factor))+
    facet_wrap(~factor, scales='free_y') +ggtitle(title)-> figL
  
  print(figL)
}


# add 'point_exponential' to the choice of flashier priors
prior.point.exponential <- function(...) {
  args <- as.prior.args(prior.family = "point_exponential",
                        optmethod = "nlm",
                        ...)
  return(do.call(as.prior, args))
}
environment(prior.point.exponential) <- asNamespace('flashier') 

plot.factors <- function(fit, showK=NULL){
  if(is.null(showK)){showK <- ncol(fit$loadings.pm[[1]])}
  
  data.frame(L=c(fit$loadings.pm[[1]][,1:showK]), 
           x=rep(1:80),
           factor=as.factor(rep(1:showK, 
                      each=80))) %>%
  ggplot()+geom_line(aes(x=x, y=L, col=factor))
}

```



# toy data

```{r}
set.seed(1)

n <- 150
p <- 240
K <- 3
tau <- 1

L <- matrix(0, nrow=n, ncol=K)
F <- matrix(0, nrow=p, ncol=K)
L[1:10,1] <- rexp(10, rate=1/10)
L[11:60,2] <- rexp(50, rate=1/5)
L[61:150,3] <- rexp(90, rate=1)
F[1:80, 1] <- rnorm(80, sd=1)
F[81:160,2] <- rnorm(80, sd=1)
F[161:240,3] <- rnorm(80, sd=1)
E <- matrix(rnorm(n*p, mean=0, sd=tau^(-1/2)), nrow=n, ncol=p)

X0 <- L %*% t(F)
X <- X0 + E
```


# altflash vs flashier


```{r}
library(flashier)
fit.flashier <- flash(X, prior.family=c(prior.point.exponential(), prior.point.normal()),
                      backfit=TRUE, verbose.lvl=0)
fit.flashier$n.factors
fit.flashier$elbo
plotL(fit.flashier$loadings.pm[[1]], "flashier EL")

fit.alt <- altflash(X, initial.K=5, prior.family=c('point_exponential', 'point_normal'), verbose=0)
last(fit.alt$elbo.vec)
plotL(fit.alt$EL, "altflash EL")
```

### if set K=1, the result is identical to the flashier fit

```{r}
fit.alt.1 <- altflash(X, initial.K=1, prior.family=c('point_exponential', 'point_normal'), verbose=0)
last(fit.alt.1$elbo.vec)
plotL(fit.alt.1$EL, "altflash EL")
```

### try different random initializations for flashier

```{r}
for (seed in 2:5){
  fit.alt <- altflash(X, initial.K=5, prior.family=c('point_exponential', 'point_normal'), verbose=0, seed=seed)
  print(last(fit.alt$elbo.vec))
  plotL(fit.alt$EL, "altflash EL")
}
```


# another toy

```{r}
# source: https://yushaliu.github.io/single_cell_cancer/simulations3_update.html
model <- readRDS(url("https://raw.githubusercontent.com/YushaLiu/single_cell_cancer/master/data/model.rds"))
L <- model$L
F <- model$F
F[,1] <- F[,1] - 10 # center the data

X <- L%*%t(F) + matrix(rnorm(800*2000, 0, 0.5), nrow=800, ncol=2000)
```


```{r}
library(flashier)
fit.flashier <- flash(X, prior.family=c(prior.point.exponential(), prior.point.normal()),
                      backfit=TRUE, verbose.lvl=0)
fit.flashier$n.factors
fit.flashier$elbo
plotL(fit.flashier$loadings.pm[[1]], "flashier EL")

fit.alt <- altflash(X, initial.K=15, prior.family=c('point_exponential', 'point_normal'), verbose=0)
last(fit.alt$elbo.vec)
plotL(fit.alt$EL, "altflash EL")
``` 
